/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package pl.xpu.html.validator

import spock.lang.Specification
import spock.lang.Unroll

class HtmlDocumentValidatorTest extends Specification {

	@Unroll
	void "validateHtml: check errors as string"() {
		given:
			HtmlDocumentValidator htmlValidator = new HtmlDocumentValidator()
		expect:
			htmlValidator.validateHtmlDocument(htmlContent) == expectedErrors

		where:
			htmlContent                                                                               || expectedErrors
			"test"                                                                                    || '{"messages":[{"type":"error","lastLine":1,"lastColumn":3,"firstColumn":1,"message":"Non-space characters found without seeing a doctype first. Expected “<!DOCTYPE html>”.","extract":"test","hiliteStart":0,"hiliteLength":3},{"type":"error","lastLine":1,"lastColumn":3,"firstColumn":1,"message":"Element “head” is missing a required instance of child element “title”.","extract":"test","hiliteStart":0,"hiliteLength":3}]}\n'
			"<!DOCTYPE html><html lang='en'><head><title>t</title></head><body>content</body></html>" || '{"messages":[]}\n'
	}
}
